Jahia/personal-api-tokens

- .circleci/config.yml
- tests/.env.example
- tests/package.json
- tests/yarn.lock
> Modified the snapshot tag for the dev image

- pom.xml
- tests/cypress.json
- tests/yarn.lock
- yarn.lock
Reorder test files to address flakiness in tests
> Reorder test files to address flakiness in tests

- package.json
- src/main/javascript/PersonalApiTokens/MyApiTokens/MyApiTokens.jsx
- src/main/javascript/PersonalApiTokens/UserApiTokens/UserApiTokens.jsx
- src/main/javascript/index.js
- src/test/javascript/__tests__/__snapshots__/mainScreenSnapshot.test.jsx.snap
- src/test/javascript/__tests__/__snapshots__/tokenToggleState.test.jsx.snap
- webpack.config.js
- yarn.lock
https://jira.jahia.org/browse/TECH-425
> TECH-425: Webpack fixes, update libs

- src/main/java/org/jahia/modules/apitokens/core/TokenAuthValve.java
Allows to add servlet mapping by adding allow-api-token property
> TECH-425: Allow to register new servlets using api tokens

- package.json
- src/main/javascript/PersonalApiTokens/MyApiTokens/MyApiTokens.jsx
https://jira.jahia.org/browse/BACKLOG-16286
Clear user token info once after mutation
> BACKLOG-16286 Clear user token info once after mutation

- .circleci/config.yml
https://jira.jahia.org/browse/BACKLOG-17079
> BACKLOG-17079 - Unlock CircleCI workflow for the release

- package.json
https://jira.jahia.org/browse/TECH-728
> TECH-728 - Fix build on Windows

- package.json
https://jira.jahia.org/browse/TECH-728
> TECH-728 - Fix build on Windows (#106)

- .github/workflows/on-code-change.yml
- package.json
- src/main/import/permissions.xml
- src/main/java/org/jahia/modules/apitokens/graphql/GqlPersonalApiTokensMutation.java
- src/main/javascript/PersonalApiTokens.register.jsx
- src/test/javascript/__tests__/__snapshots__/mainScreenSnapshot.test.jsx.snap
- src/test/javascript/__tests__/__snapshots__/tokenToggleState.test.jsx.snap
- tests/cypress/fixtures/createRoles.graphql
- tests/cypress/fixtures/deleteRoles.graphql
- tests/cypress/integration/api/createToken.spec.ts
- tests/cypress/integration/api/deleteToken.spec.ts
- tests/cypress/integration/api/listTokens.spec.ts
- tests/cypress/integration/api/paginationOrdering.spec.ts
- tests/cypress/integration/api/updateToken.spec.ts
- tests/cypress/integration/api/useToken.spec.ts
- tests/cypress/integration/api/workspace.spec.example.ts
- tests/cypress/integration/myTokensE2E.spec.ts
- tests/cypress/integration/setupRoles.ts
- tests/cypress/integration/userTokensE2E.spec.ts
- webpack.config.js
- yarn.lock
https://jira.jahia.org/browse/QA-14308
> QA-14308 adds permission

- tests/package.json
- tests/yarn.lock
https://jira.jahia.org/browse/BACKLOG-17248
> BACKLOG-17248: More security vulnerability patches

- pom.xml
- src/main/resources/META-INF/definitions.cnd
https://jira.jahia.org/browse/QA-14499
> QA-14499: Do not export tokens

- src/main/resources/javascript/locales/de.json
- src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/QA-14418
> QA-14418 - Provide translations

- .github/workflows/manual-run.yml
- .github/workflows/milestone.yml
- .github/workflows/nightly.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
- pom.xml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
> TECH-1081 Update deprecated steps

- pom.xml
https://jira.jahia.org/browse/TECH-1091
Update jahia-depends
> TECH-1091 Update jahia-depends

- package.json
- pom.xml
- yarn.lock
https://jira.jahia.org/browse/TECH-1319
> TECH-1319: Add sync-pom configuration

- .github/workflows/nightly.yml
> Split reporting between Jahia SN and Jahia RL

- pom.xml
https://jira.jahia.org/browse/TECH-1597
> TECH-1597: Add missing import package

- .github/workflows/manual-run.yml
- .github/workflows/milestone.yml
- .github/workflows/nightly.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- .github/workflows/on-release.yml
- .github/workflows/on-rollback.yml
- .github/workflows/schedule-sonar.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
> TECH-1639 Upgrade actions 

- src/main/javascript/PersonalApiTokens/ScopesSelector/ScopesSelector.jsx
Fix dialog title alignment  by removing canResize: false
The following are included in this PR
I have considered the following implications of my change:
> fix: align title

- src/main/javascript/PersonalApiTokens/ScopesSelector/ScopesSelector.scss
Fix background color on table's header.
When scrolling the content was correctly displayed under the header but it had no background because of a rule that took priority to the one supposed to be effective.
The following are included in this PR
I have considered the following implications of my change:
> fix: fix table header bg-color on creation
